#!/usr/bin/env bash
if [[ "$#" > 0 ]]
then
    SCRIPT_PATH=$(dirname `which $0`)
    echo "SCRIPT=$SCRIPT_PATH"
    for w in "$@"
    do
        echo "===== $w ====="
        java -jar $SCRIPT_PATH/whiley2boogie.jar "$w" &&
        boogie /timeLimit:10 $SCRIPT_PATH/../wval.bpl ${w%.whiley}.bpl
    done
else
    echo "Usage: $0 *.whiley"
fi

