#!/usr/bin/env bash
if [[ "$#" > 0 ]]
then
    num_compile_errors=$(grep -i '^ *^' "$@" | wc -l)
    num_not_impl=$(grep -i '^Exception in.*NotImplementedYet:' "$@" | wc -l)
    num_exceptions=$(grep '^Exception in ' "$@" | grep -v NotImplementedYet | wc -l)
    num_bpl_errors=$(grep -i '^[A-Z][A-Za-z0-9_]*.bpl(.*Error:' "$@" | sed -e 's/(.*//' | uniq | wc -l)
    num_fully_verified=$(grep -i ' verified, 0 errors$' "$@" | wc -l)
    num_timeouts=$(grep -i ', [1-9][0-9]* time out' "$@" | wc -l)
    num_partial_verified=$(grep -i ' verified, [1-9][0-9]* error[s]*$' "$@" | wc -l)
    total=$((num_compile_errors + num_not_impl + num_exceptions + num_bpl_errors +
             num_fully_verified + num_timeouts + num_partial_verified))

    echo -e "Error Compiling:    $num_compile_errors \t$((100*num_compile_errors/total))%"
    echo -e "NotImplementedYet:  $num_not_impl \t$((100*num_not_impl/total))%"
    echo -e "Other Exceptions:   $num_exceptions \t$((100*num_exceptions/total))%"
    echo -e "Errors in BPL:      $num_bpl_errors \t$((100*num_bpl_errors/total))%"
    echo -e "Fully Verified:     $num_fully_verified \t$((100*num_fully_verified/total))%"
    echo -e "Verify time outs:   $num_timeouts \t$((100*num_timeouts/total))%"
    echo -e "Verify errors:      $num_partial_verified \t$((100*num_partial_verified/total))%"
    echo "Total:  $total"
else
    echo "Usage: $0 OUT*.txt"
    exit 1
fi
